# Weekly Payment System for Highridge Construction Company
# R implementation with enhanced readability and error handling

#' Generate simulated workforce data
#' 
#' @param num_workers Number of workers to generate
#' @return Data frame containing employee records
set.seed(123)  # For reproducibility

generate_workers <- function(num_workers) {
  workers <- data.frame(
    name = paste0("Employee #-", 1:num_workers),
    salary = sample(2000:35000, num_workers, replace = TRUE),
    gender = sample(c("Male", "Female"), num_workers, replace = TRUE),
    level = character(num_workers),
    stringsAsFactors = FALSE
  )
  return(workers)
}
#' Generate payment slips and assign pay grades
#' 
#' @param workers Data frame generated by generate_workers
#' @return Updated data frame with pay grades

generate_payment_slips <- function(workers) {
  # Process each employee record
  for (i in 1:nrow(workers)) {
    tryCatch({
      salary <- workers$salary[i]
      gender <- workers$gender[i]
      level <- "Unclassified" #default
      
      #Determine level based on salary and gender
      if (salary > 10000 & salary < 20000) {
        level <- "A1"
      } else if (salary > 7500 & salary < 30000 & gender == "Female") {
        level <- "A5-F"
      }
      #Update worker record with level
      workers$level[i] <- level
      
      #Generate the payslip output
      cat(sprintf("Payment slip for: %s, Gender: %s\n, Salary: $%d, Level: %s\n", 
                  workers$name[i], gender, salary, level))
    }, error = function(e) {
      cat(sprintf("Error processing worker %d: %s\n", i, e$message))
    })
  }
  return(workers)
}

# Execute
#configuration contstants
workers <- generate_workers(400)
#generate and process workers data
workers <- generate_payment_slips(workers)

